-- VHDL module instantiation generated by SCUBA Diamond (64-bit) 3.12.1.454
-- Module  Version: 5.7
-- Fri May 17 18:07:51 2024

-- parameterized module component declaration
component PLL
    port (CLKI: in  std_logic; CLKOP: out  std_logic; 
        CLKOS2: out  std_logic; CLKOS3: out  std_logic; 
        LOCK: out  std_logic);
end component;

-- parameterized module component instance
__ : PLL
    port map (CLKI=>__, CLKOP=>__, CLKOS2=>__, CLKOS3=>__, LOCK=>__);
